import sys
top = "."
out = "build"

REQUIRED_TOOLCHAINS = ["gccarmemb"]
HILSCHER_VERSION_COMPATIBILITY = '1.10.1.0'

def options(ctx):
    try:
        ctx.load("hilscher_netx hilscher_firmware hilscher_extras", tooldir="WAF")
        print("Loaded WAF options from project.")
    except:
        ctx.load("hilscher_netx hilscher_firmware hilscher_extras")
        print("Loaded WAF options from netX Studio.")
    from hilscher_netx import HILSCHER_VERSION
    if (HILSCHER_VERSION < HILSCHER_VERSION_COMPATIBILITY):
        sys.stderr.write("Hilscher Waf V" + HILSCHER_VERSION + " is not recommended, please use at least V" + HILSCHER_VERSION_COMPATIBILITY + " or newer!\n")
    sys.stdout.flush()
    ctx.autorecurse(mandatory=False)

def configure(conf):
    try:
        conf.load("hilscher_netx hilscher_firmware hilscher_extras", tooldir="WAF")
        print("Loaded WAF configuration from project.")
    except:
        conf.load("hilscher_netx hilscher_firmware hilscher_extras")
        print("Loaded WAF configuration from netX Studio.")
    sys.stdout.flush()
    conf.autorecurse(mandatory=False)

def dist(bld):
    pass

def build(bld):
    bld.autorecurse() 
